# Numpy DZ1

## Task 1

In [2]:
import numpy as np

In [13]:
arr = np.random.randint(1, 51, size=(4, 4))

4


In [25]:
for i in arr:
    for j in i:
        print(j, end=" | ")
    print(end="\n")
    print("-----------------")

36 | 22 | 17 | 26 | 
-----------------
16 | 4 | 2 | 27 | 
-----------------
20 | 9 | 14 | 46 | 
-----------------
50 | 34 | 31 | 18 | 
-----------------


In [28]:
col_sums = arr.sum(axis=0)
row_sums = arr.sum(axis=1)

[122  69  64 117]
[101  49  89 133]


In [30]:
mean_val = arr.mean()

In [31]:
print("Row sums:", row_sums)
print("Col sums:", col_sums)
print("General mean value:", mean_val)

Row sums: [101  49  89 133]
Col sums: [122  69  64 117]
General mean value: 23.25


## Task 2

In [34]:
arr2 = np.arange(0, 15).reshape(3, 5)

print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [37]:
transposed = arr2.T

In [40]:
reshaped = arr2.reshape(5, 3)

In [42]:
print(transposed)
print(reshaped)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Task 3

### Отчет по продажам

В этом разделе мы считаем итоги по простым данным

In [43]:
sales = np.array([120, 135, 100, 150, 90, 200, 170])

In [45]:
sales_sum = sales.sum()
average_sales = sales.mean()
max_val = sales.max()
min_val = sales.min()

print(sales_sum)
print(average_sales)
print(max_val)
print(min_val)

965
137.85714285714286
200
90


| Показатель  | Значение |
|-------------|----------|
| Общая сумма | 965      |
| Среднее     | 137.86   |
| Максимум    | 200      |
| Минимум     | 90       |